### ISSUE TITLE
need to handle unknown stream info

### ISSUE THREAD

**Issue by nergdron** [nergdron/dve#1]
Have discovered an issue where encoding fails when unknown streams (such as TTFs for subs) are found. Need to come up with a graceful way to handle this, preferably with those streams ending up in the output merged file.

**Comment by nergdron** [comment]
Note that in latest release, this bug breaks distributed encoding, so probably need to implement a real fix. Pull out unrecognized streams independently, and then recopy into final encoded output?

**Comment by zenny** [comment]
Has this been fixed in the last two and half years? Just curious!

**Comment by nergdron** [comment]
I did a rewrite a few months back that may have fixed this, I'll have to verify actually. Thanks for pinging, I'll try to check soon!

**Comment by nergdron** [comment]
Nope, just double checked, still appears to be broken. Sorry. I'm honestly not sure of a good way to detect and mux in those extra tracks from an original video after encoding. If there's any suggestions on how to approach that, I'll implement it.

**Comment by nergdron** [comment]
Did some digging in the docs and found a way to do this that should work with just about any input data. It works with my test files, if you could test on your end and see how it looks for confirmation, I'd really appreciate it!
